name: freebase_searchwidget
version: 0.1.2
author: Günter Zöchbauer <guenter@gzoechbauer.com>
homepage: https://github.com/zoechi/dart-freebase-search-widget
description: Dart port of Google's Freebase Suggest 4.2 Javascript/jQuery component.
environment:
  sdk: any
dependencies:
  polymer: any
  animation: any
#  mdv: any
  browser: any
  
dev_dependencies:
  unittest: any
